Fix #100 : Generate YAML compatible text
cookpad/license-tools-plugin pull request #101
Opened 2018-10-18 00:48 UTC by jmatsu

Fix #100

This plugin has been generating text by appending Strings manually, and it broke YAML compatibility in some cases.
e.g. one of the attributes includes a column with spaces, i.e. " : ".

This change allows the plugin to generate YAML compatible text like below.

```
- "artifact": "com.cookpad.android:licensetools:+"
  "name": "licensetools"
  "copyrightHolder": "#AUTHOR# (or authors: [...])"
  "year": "#YEAR# (optional)"
```

2018-10-30 03:50 UTC, litmon requested changes
Thank you for contributing and I apologize for late review 🙇

2018-10-30 03:50 UTC, litmon commented on plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy
> +            datum["copyrightHolder"] = "#AUTHOR# (or authors: [...])"
It doesn't make comment-out string by `YAML.dump()`, so it will be happened that "#AUTHOR#" shows generated HTML. You must add validation for comment-out columns. Or you must generate comment-out string if you can.

2018-10-30 03:50 UTC, litmon commented on plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy
> +            defaultScalarStyle = ScalarStyle.DOUBLE_QUOTED
I prefer style `ScalarStyle.PLAIN` to this.

2018-11-16 05:12 UTC, jmatsu commented
Thank you for your reviews and sorry to be late.
 I'll address them with a few days, thanks.

2019-04-30 07:30 UTC, jmatsu commented
#116 sounds better because SnakeYAML cannot treat comments in YAML documents as expected. 
Let me close this. Thank you for your review, and apologize for the lazy response.

2019-04-30 07:30 UTC, closed without merging