Add updateLicenses task to append missing libraries to licenses.yml
cookpad/license-tools-plugin pull request #60
Opened 2017-07-31 10:58 UTC by rockwillj

(This PR was split from https://github.com/cookpad/license-tools-plugin/pull/51)

`How To Use` says that you will **see** the following messages by running the `checkLicenses` task.

```
- artifact: com.android.support:support-v4:+
  name: #NAME#
  copyrightHolder: #AUTHOR#
  license: No license found
- artifact: com.android.support:animated-vector-drawable:+
  name: #NAME#
  copyrightHolder: #AUTHOR#
  license: No license found
- artifact: io.reactivex:rxjava:+
  name: #NAME#
  copyrightHolder: #AUTHOR#
  license: apache2
```

It is a little bit annoying for me to copy and paste the messages from console to `licenses.yml`.
So I add new `updateLicenses` task to append not-listed libraries to `licenses.yml` automatically.

2017-10-13 05:07 UTC, litmon requested changes

2017-10-13 05:07 UTC, litmon commented on plugin/src/main/groovy/com/cookpad/android/licensetools/LicenseToolsPlugin.groovy
> +        updateLicenses.dependsOn('checkLicenses')
`updateLicenses` might not be execute if `checkLicenses` failed.
so please remove this line. it should be declared on each projects.

2018-05-11 11:02 UTC, iamutkarshtiwari commented
@rockwillj If you aren't working on this PR anymore, can I make a new PR with these changes?

2018-05-21 02:21 UTC, ghost commented
close this because of _Add updatelicense task for auto addition of licenses to `licenses.yml` #86_

Thanks for your commitment 👍

2018-05-21 02:21 UTC, closed without merging