add the way to reduce boilerplate code
cookpad/license-tools-plugin pull request #76
Opened 2018-01-13 17:49 UTC by KazuCocoa

2018-01-14 04:47 UTC, koyama-kani-daisuki requested changes

2018-01-14 04:47 UTC, nein37 commented on example/build.gradle
> +def implementation_project(name) {
Please use `path` for argument name.

2018-01-14 05:16 UTC, KazuCocoa commented
✔️

2018-01-15 07:15 UTC, koyama-kani-daisuki approved these changes

2018-01-15 07:26 UTC, merged